version: '{build}'
environment:
  CLI_VERSION: latest
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:  
  - ps: .\build.ps1
test: off
artifacts:  
- path: .\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  api_key:
    secure: mj0BtY16CsWT3mvEQvUAm5VpRVCdkmjGtEfyzjrMZMKYJ/Izy7waJhlAgmLtpi4I